name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        enable_ui: [on]
        include:
          - os: windows-latest
            build_type: Release
            enable_ui: on

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # Cache build tools using ccache (only for Linux, currently not applicable to this Windows-only workflow)
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      if: runner.os == 'Linux'
      with:
        key: ${{ matrix.os }}-${{ matrix.enable_ui }}

    # Set up Ninja build system
    - uses: seanmiddleditch/gha-setup-ninja@master

    # Set up MSVC developer command prompt (Windows-specific)
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    # Install dependencies (conditionally for Linux)
    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libx11-dev libxcursor-dev libxi-dev

    # Generate Makefiles using CMake
    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi
        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
        7z x skia.zip
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_UI=${{ matrix.enable_ui }} \
          -DENABLE_CCACHE=$enable_ccache \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

    # Build the project
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja

    # Upload build artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aseprite
        path: |
          D:/a/aseprite/aseprite/build/bin/data
          D:/a/aseprite/aseprite/build/bin/aseprite.exe
